#playbook para registro do GitLab Runner. Fonte: https://github.com/riemers/ansible-gitlab-runner
#Editado por: Matheus Medeiros
- hosts: app
  become: true
  vars_files:
    - vars/app.yml
  roles:
    - { role: riemers.gitlab-runner }
