#arquivo para acionar playbooks em sequência.
#Autor: Matheus Medeiros
- name: Install_Docker
  import_playbook: provi_docker.yml

- name: Register_GitLab_runner_app
  import_playbook: gitlab-runner-app.yml

