#playbook instala a engine docker e faz o registro no gitlabRunner
- name: Install_Docker
  import_playbook: provi_docker.yml

- name: Register_GitLab_runner_app
  import_playbook: gitlab-runner-app.yml

